/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class shop_memall_diff_diffserver_bridge_JNIBridge */
#include <jni.h>


#ifndef _Included_shop_memall_diff_diffserver_bridge_JNIBridge
#define _Included_shop_memall_diff_diffserver_bridge_JNIBridge
#ifdef __cplusplus


extern "C" {
#endif
/*
 * Class:     shop_memall_diff_diffserver_bridge_JNIBridge
 * Method:    createPatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_shop_memall_diff_diffserver_bridge_JNIBridge_createPatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
